// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqcfunbdlidmfqmltozp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxY2Z1bmJkbGlkbWZxbWx0b3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzc0MDQsImV4cCI6MjA2NTcxMzQwNH0.-YtsvT9WjPTBW5XMMeCJNc7Wo1fWE0eHuLDsZ3Opzcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});